/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * keitaito.net Activities API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActivitiesCreateBody,
  ActivitiesUpdateBody,
  Activity
} from '.././model';




  /**
 * Retrieve a list of all activities
 * @summary List all activities
 */
export const activitiesList = <TData = AxiosResponse<Activity[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/activities`,options
    );
  }
/**
 * Create a new activity with the provided details
 * @summary Create a new activity
 */
export const activitiesCreate = <TData = AxiosResponse<Activity>>(
    activitiesCreateBody: ActivitiesCreateBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/activities`,
      activitiesCreateBody,options
    );
  }
/**
 * Retrieve a single activity by ID
 * @summary Get an activity
 */
export const activitiesGet = <TData = AxiosResponse<Activity>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/activities/${id}`,options
    );
  }
/**
 * Update an existing activity by ID
 * @summary Update an activity
 */
export const activitiesUpdate = <TData = AxiosResponse<Activity>>(
    id: string,
    activitiesUpdateBody: ActivitiesUpdateBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/activities/${id}`,
      activitiesUpdateBody,options
    );
  }
/**
 * Delete an existing activity by ID
 * @summary Delete an activity
 */
export const activitiesDelete = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/activities/${id}`,options
    );
  }
export type ActivitiesListResult = AxiosResponse<Activity[]>
export type ActivitiesCreateResult = AxiosResponse<Activity>
export type ActivitiesGetResult = AxiosResponse<Activity>
export type ActivitiesUpdateResult = AxiosResponse<Activity>
export type ActivitiesDeleteResult = AxiosResponse<void>
