services:
  www:
    build:
      context: .
      dockerfile: apps/www/Dockerfile
      args:
        - CUSTOM_URL=${CUSTOM_URL}
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
        - SUPABASE_URL=${SUPABASE_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
