packages:
  - server
  - www

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - core-js-pure
  - esbuild
  - lefthook
  - prisma
  - sharp
  - unrs-resolver
