packages:
  - server
  - www

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - esbuild
  - lefthook
  - prisma
