/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ActivitiesCreateBody,
  ActivitiesUpdateBody,
  Activity
} from './models';

import { customInstance } from '../server-axios';
import type { BodyType } from '../server-axios';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Retrieve a list of all activities
 * @summary List all activities
 */
export const activitiesList = (
    
 options?: SecondParameter<typeof customInstance<Activity[]>>,) => {
      return customInstance<Activity[]>(
      {url: `/activities`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a new activity with the provided details
 * @summary Create a new activity
 */
export const activitiesCreate = (
    activitiesCreateBody: BodyType<ActivitiesCreateBody>,
 options?: SecondParameter<typeof customInstance<Activity>>,) => {
      return customInstance<Activity>(
      {url: `/activities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: activitiesCreateBody
    },
      options);
    }
  
/**
 * Retrieve a single activity by ID
 * @summary Get an activity
 */
export const activitiesGet = (
    id: string,
 options?: SecondParameter<typeof customInstance<Activity>>,) => {
      return customInstance<Activity>(
      {url: `/activities/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update an existing activity by ID
 * @summary Update an activity
 */
export const activitiesUpdate = (
    id: string,
    activitiesUpdateBody: BodyType<ActivitiesUpdateBody>,
 options?: SecondParameter<typeof customInstance<Activity>>,) => {
      return customInstance<Activity>(
      {url: `/activities/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: activitiesUpdateBody
    },
      options);
    }
  
/**
 * Delete an existing activity by ID
 * @summary Delete an activity
 */
export const activitiesDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/activities/${id}`, method: 'DELETE'
    },
      options);
    }
  
export type ActivitiesListResult = NonNullable<Awaited<ReturnType<typeof activitiesList>>>
export type ActivitiesCreateResult = NonNullable<Awaited<ReturnType<typeof activitiesCreate>>>
export type ActivitiesGetResult = NonNullable<Awaited<ReturnType<typeof activitiesGet>>>
export type ActivitiesUpdateResult = NonNullable<Awaited<ReturnType<typeof activitiesUpdate>>>
export type ActivitiesDeleteResult = NonNullable<Awaited<ReturnType<typeof activitiesDelete>>>
