/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ActivitiesCreateBody,
  ActivitiesUpdateBody,
  Activity,
  Contact,
  ContactUpdateBody,
  Profile,
  ProfileUpdateBody,
  Skill,
  SkillsCreateBody,
  SkillsUpdateBody,
  Work,
  WorksCreateBody,
  WorksUpdateBody
} from './models';

import { customInstance } from '../server-axios';
import type { BodyType } from '../server-axios';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * Retrieve a list of all activities
 * @summary List all activities
 */
export const activitiesList = (
    
 options?: SecondParameter<typeof customInstance<Activity[]>>,) => {
      return customInstance<Activity[]>(
      {url: `/activities`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a new activity with the provided details
 * @summary Create a new activity
 */
export const activitiesCreate = (
    activitiesCreateBody: BodyType<ActivitiesCreateBody>,
 options?: SecondParameter<typeof customInstance<Activity>>,) => {
      return customInstance<Activity>(
      {url: `/activities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: activitiesCreateBody
    },
      options);
    }
  
/**
 * Retrieve a single activity by ID
 * @summary Get an activity
 */
export const activitiesGet = (
    id: string,
 options?: SecondParameter<typeof customInstance<Activity>>,) => {
      return customInstance<Activity>(
      {url: `/activities/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update an existing activity by ID
 * @summary Update an activity
 */
export const activitiesUpdate = (
    id: string,
    activitiesUpdateBody: BodyType<ActivitiesUpdateBody>,
 options?: SecondParameter<typeof customInstance<Activity>>,) => {
      return customInstance<Activity>(
      {url: `/activities/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: activitiesUpdateBody
    },
      options);
    }
  
/**
 * Delete an existing activity by ID
 * @summary Delete an activity
 */
export const activitiesDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/activities/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Retrieve a list of all skills
 * @summary List all skills
 */
export const skillsList = (
    
 options?: SecondParameter<typeof customInstance<Skill[]>>,) => {
      return customInstance<Skill[]>(
      {url: `/skills`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a new skill with the provided details
 * @summary Create a new skill
 */
export const skillsCreate = (
    skillsCreateBody: BodyType<SkillsCreateBody>,
 options?: SecondParameter<typeof customInstance<Skill>>,) => {
      return customInstance<Skill>(
      {url: `/skills`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: skillsCreateBody
    },
      options);
    }
  
/**
 * Retrieve a single skill by ID
 * @summary Get a skill
 */
export const skillsGet = (
    id: string,
 options?: SecondParameter<typeof customInstance<Skill>>,) => {
      return customInstance<Skill>(
      {url: `/skills/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update an existing skill by ID
 * @summary Update a skill
 */
export const skillsUpdate = (
    id: string,
    skillsUpdateBody: BodyType<SkillsUpdateBody>,
 options?: SecondParameter<typeof customInstance<Skill>>,) => {
      return customInstance<Skill>(
      {url: `/skills/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: skillsUpdateBody
    },
      options);
    }
  
/**
 * Delete an existing skill by ID
 * @summary Delete a skill
 */
export const skillsDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/skills/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Retrieve a list of all works
 * @summary List all works
 */
export const worksList = (
    
 options?: SecondParameter<typeof customInstance<Work[]>>,) => {
      return customInstance<Work[]>(
      {url: `/works`, method: 'GET'
    },
      options);
    }
  
/**
 * Create a new work with the provided details
 * @summary Create a new work
 */
export const worksCreate = (
    worksCreateBody: BodyType<WorksCreateBody>,
 options?: SecondParameter<typeof customInstance<Work>>,) => {
      return customInstance<Work>(
      {url: `/works`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: worksCreateBody
    },
      options);
    }
  
/**
 * Retrieve a single work by ID
 * @summary Get a work
 */
export const worksGet = (
    id: string,
 options?: SecondParameter<typeof customInstance<Work>>,) => {
      return customInstance<Work>(
      {url: `/works/${id}`, method: 'GET'
    },
      options);
    }
  
/**
 * Update an existing work by ID
 * @summary Update a work
 */
export const worksUpdate = (
    id: string,
    worksUpdateBody: BodyType<WorksUpdateBody>,
 options?: SecondParameter<typeof customInstance<Work>>,) => {
      return customInstance<Work>(
      {url: `/works/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: worksUpdateBody
    },
      options);
    }
  
/**
 * Delete an existing work by ID
 * @summary Delete a work
 */
export const worksDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/works/${id}`, method: 'DELETE'
    },
      options);
    }
  
/**
 * Retrieve the profile
 * @summary Get profile
 */
export const profileGet = (
    
 options?: SecondParameter<typeof customInstance<Profile>>,) => {
      return customInstance<Profile>(
      {url: `/profile`, method: 'GET'
    },
      options);
    }
  
/**
 * Create or update the profile (upsert)
 * @summary Update profile
 */
export const profileUpdate = (
    profileUpdateBody: BodyType<ProfileUpdateBody>,
 options?: SecondParameter<typeof customInstance<Profile>>,) => {
      return customInstance<Profile>(
      {url: `/profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: profileUpdateBody
    },
      options);
    }
  
/**
 * Retrieve the contact information
 * @summary Get contact
 */
export const contactGet = (
    
 options?: SecondParameter<typeof customInstance<Contact>>,) => {
      return customInstance<Contact>(
      {url: `/contact`, method: 'GET'
    },
      options);
    }
  
/**
 * Create or update the contact information (upsert)
 * @summary Update contact
 */
export const contactUpdate = (
    contactUpdateBody: BodyType<ContactUpdateBody>,
 options?: SecondParameter<typeof customInstance<Contact>>,) => {
      return customInstance<Contact>(
      {url: `/contact`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: contactUpdateBody
    },
      options);
    }
  
export type ActivitiesListResult = NonNullable<Awaited<ReturnType<typeof activitiesList>>>
export type ActivitiesCreateResult = NonNullable<Awaited<ReturnType<typeof activitiesCreate>>>
export type ActivitiesGetResult = NonNullable<Awaited<ReturnType<typeof activitiesGet>>>
export type ActivitiesUpdateResult = NonNullable<Awaited<ReturnType<typeof activitiesUpdate>>>
export type ActivitiesDeleteResult = NonNullable<Awaited<ReturnType<typeof activitiesDelete>>>
export type SkillsListResult = NonNullable<Awaited<ReturnType<typeof skillsList>>>
export type SkillsCreateResult = NonNullable<Awaited<ReturnType<typeof skillsCreate>>>
export type SkillsGetResult = NonNullable<Awaited<ReturnType<typeof skillsGet>>>
export type SkillsUpdateResult = NonNullable<Awaited<ReturnType<typeof skillsUpdate>>>
export type SkillsDeleteResult = NonNullable<Awaited<ReturnType<typeof skillsDelete>>>
export type WorksListResult = NonNullable<Awaited<ReturnType<typeof worksList>>>
export type WorksCreateResult = NonNullable<Awaited<ReturnType<typeof worksCreate>>>
export type WorksGetResult = NonNullable<Awaited<ReturnType<typeof worksGet>>>
export type WorksUpdateResult = NonNullable<Awaited<ReturnType<typeof worksUpdate>>>
export type WorksDeleteResult = NonNullable<Awaited<ReturnType<typeof worksDelete>>>
export type ProfileGetResult = NonNullable<Awaited<ReturnType<typeof profileGet>>>
export type ProfileUpdateResult = NonNullable<Awaited<ReturnType<typeof profileUpdate>>>
export type ContactGetResult = NonNullable<Awaited<ReturnType<typeof contactGet>>>
export type ContactUpdateResult = NonNullable<Awaited<ReturnType<typeof contactUpdate>>>
