/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivitiesCreateBody,
  ActivitiesUpdateBody,
  Activity,
  ErrorResponse,
  Profile,
  ProfileUpdateBody,
  Skill,
  SkillsCreateBody,
  SkillsUpdateBody,
  Work,
  WorksCreateBody,
  WorksUpdateBody
} from './models';

import { customInstance } from '../client-axios';
import type { ErrorType , BodyType } from '../client-axios';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve a list of all activities
 * @summary List all activities
 */
export const activitiesList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Activity[]>(
      {url: `/activities`, method: 'GET', signal
    },
      options);
    }
  



export const getActivitiesListQueryKey = () => {
    return [
    `/activities`
    ] as const;
    }

    
export const getActivitiesListQueryOptions = <TData = Awaited<ReturnType<typeof activitiesList>>, TError = ErrorType<void | ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActivitiesListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof activitiesList>>> = ({ signal }) => activitiesList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof activitiesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActivitiesListQueryResult = NonNullable<Awaited<ReturnType<typeof activitiesList>>>
export type ActivitiesListQueryError = ErrorType<void | ErrorResponse>


export function useActivitiesList<TData = Awaited<ReturnType<typeof activitiesList>>, TError = ErrorType<void | ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof activitiesList>>,
          TError,
          Awaited<ReturnType<typeof activitiesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActivitiesList<TData = Awaited<ReturnType<typeof activitiesList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof activitiesList>>,
          TError,
          Awaited<ReturnType<typeof activitiesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActivitiesList<TData = Awaited<ReturnType<typeof activitiesList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all activities
 */

export function useActivitiesList<TData = Awaited<ReturnType<typeof activitiesList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActivitiesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Create a new activity with the provided details
 * @summary Create a new activity
 */
export const activitiesCreate = (
    activitiesCreateBody: BodyType<ActivitiesCreateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Activity>(
      {url: `/activities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: activitiesCreateBody, signal
    },
      options);
    }
  


export const getActivitiesCreateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesCreate>>, TError,{data: BodyType<ActivitiesCreateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activitiesCreate>>, TError,{data: BodyType<ActivitiesCreateBody>}, TContext> => {

const mutationKey = ['activitiesCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activitiesCreate>>, {data: BodyType<ActivitiesCreateBody>}> = (props) => {
          const {data} = props ?? {};

          return  activitiesCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ActivitiesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof activitiesCreate>>>
    export type ActivitiesCreateMutationBody = BodyType<ActivitiesCreateBody>
    export type ActivitiesCreateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Create a new activity
 */
export const useActivitiesCreate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesCreate>>, TError,{data: BodyType<ActivitiesCreateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activitiesCreate>>,
        TError,
        {data: BodyType<ActivitiesCreateBody>},
        TContext
      > => {
      return useMutation(getActivitiesCreateMutationOptions(options), queryClient);
    }
    
/**
 * Retrieve a single activity by ID
 * @summary Get an activity
 */
export const activitiesGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Activity>(
      {url: `/activities/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getActivitiesGetQueryKey = (id: string,) => {
    return [
    `/activities/${id}`
    ] as const;
    }

    
export const getActivitiesGetQueryOptions = <TData = Awaited<ReturnType<typeof activitiesGet>>, TError = ErrorType<ErrorResponse | void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getActivitiesGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof activitiesGet>>> = ({ signal }) => activitiesGet(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof activitiesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ActivitiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof activitiesGet>>>
export type ActivitiesGetQueryError = ErrorType<ErrorResponse | void>


export function useActivitiesGet<TData = Awaited<ReturnType<typeof activitiesGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof activitiesGet>>,
          TError,
          Awaited<ReturnType<typeof activitiesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActivitiesGet<TData = Awaited<ReturnType<typeof activitiesGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof activitiesGet>>,
          TError,
          Awaited<ReturnType<typeof activitiesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useActivitiesGet<TData = Awaited<ReturnType<typeof activitiesGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get an activity
 */

export function useActivitiesGet<TData = Awaited<ReturnType<typeof activitiesGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof activitiesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getActivitiesGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Update an existing activity by ID
 * @summary Update an activity
 */
export const activitiesUpdate = (
    id: string,
    activitiesUpdateBody: BodyType<ActivitiesUpdateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Activity>(
      {url: `/activities/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: activitiesUpdateBody, signal
    },
      options);
    }
  


export const getActivitiesUpdateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesUpdate>>, TError,{id: string;data: BodyType<ActivitiesUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activitiesUpdate>>, TError,{id: string;data: BodyType<ActivitiesUpdateBody>}, TContext> => {

const mutationKey = ['activitiesUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activitiesUpdate>>, {id: string;data: BodyType<ActivitiesUpdateBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  activitiesUpdate(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ActivitiesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof activitiesUpdate>>>
    export type ActivitiesUpdateMutationBody = BodyType<ActivitiesUpdateBody>
    export type ActivitiesUpdateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Update an activity
 */
export const useActivitiesUpdate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesUpdate>>, TError,{id: string;data: BodyType<ActivitiesUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activitiesUpdate>>,
        TError,
        {id: string;data: BodyType<ActivitiesUpdateBody>},
        TContext
      > => {
      return useMutation(getActivitiesUpdateMutationOptions(options), queryClient);
    }
    
/**
 * Delete an existing activity by ID
 * @summary Delete an activity
 */
export const activitiesDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/activities/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getActivitiesDeleteMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof activitiesDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['activitiesDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activitiesDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  activitiesDelete(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ActivitiesDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof activitiesDelete>>>
    
    export type ActivitiesDeleteMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Delete an activity
 */
export const useActivitiesDelete = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activitiesDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activitiesDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getActivitiesDeleteMutationOptions(options), queryClient);
    }
    
/**
 * Retrieve a list of all skills
 * @summary List all skills
 */
export const skillsList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Skill[]>(
      {url: `/skills`, method: 'GET', signal
    },
      options);
    }
  



export const getSkillsListQueryKey = () => {
    return [
    `/skills`
    ] as const;
    }

    
export const getSkillsListQueryOptions = <TData = Awaited<ReturnType<typeof skillsList>>, TError = ErrorType<void | ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSkillsListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof skillsList>>> = ({ signal }) => skillsList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof skillsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SkillsListQueryResult = NonNullable<Awaited<ReturnType<typeof skillsList>>>
export type SkillsListQueryError = ErrorType<void | ErrorResponse>


export function useSkillsList<TData = Awaited<ReturnType<typeof skillsList>>, TError = ErrorType<void | ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillsList>>,
          TError,
          Awaited<ReturnType<typeof skillsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSkillsList<TData = Awaited<ReturnType<typeof skillsList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillsList>>,
          TError,
          Awaited<ReturnType<typeof skillsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSkillsList<TData = Awaited<ReturnType<typeof skillsList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all skills
 */

export function useSkillsList<TData = Awaited<ReturnType<typeof skillsList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSkillsListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Create a new skill with the provided details
 * @summary Create a new skill
 */
export const skillsCreate = (
    skillsCreateBody: BodyType<SkillsCreateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Skill>(
      {url: `/skills`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: skillsCreateBody, signal
    },
      options);
    }
  


export const getSkillsCreateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skillsCreate>>, TError,{data: BodyType<SkillsCreateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof skillsCreate>>, TError,{data: BodyType<SkillsCreateBody>}, TContext> => {

const mutationKey = ['skillsCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof skillsCreate>>, {data: BodyType<SkillsCreateBody>}> = (props) => {
          const {data} = props ?? {};

          return  skillsCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SkillsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof skillsCreate>>>
    export type SkillsCreateMutationBody = BodyType<SkillsCreateBody>
    export type SkillsCreateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Create a new skill
 */
export const useSkillsCreate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skillsCreate>>, TError,{data: BodyType<SkillsCreateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof skillsCreate>>,
        TError,
        {data: BodyType<SkillsCreateBody>},
        TContext
      > => {
      return useMutation(getSkillsCreateMutationOptions(options), queryClient);
    }
    
/**
 * Retrieve a single skill by ID
 * @summary Get a skill
 */
export const skillsGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Skill>(
      {url: `/skills/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getSkillsGetQueryKey = (id: string,) => {
    return [
    `/skills/${id}`
    ] as const;
    }

    
export const getSkillsGetQueryOptions = <TData = Awaited<ReturnType<typeof skillsGet>>, TError = ErrorType<ErrorResponse | void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSkillsGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof skillsGet>>> = ({ signal }) => skillsGet(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof skillsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SkillsGetQueryResult = NonNullable<Awaited<ReturnType<typeof skillsGet>>>
export type SkillsGetQueryError = ErrorType<ErrorResponse | void>


export function useSkillsGet<TData = Awaited<ReturnType<typeof skillsGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillsGet>>,
          TError,
          Awaited<ReturnType<typeof skillsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSkillsGet<TData = Awaited<ReturnType<typeof skillsGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillsGet>>,
          TError,
          Awaited<ReturnType<typeof skillsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSkillsGet<TData = Awaited<ReturnType<typeof skillsGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a skill
 */

export function useSkillsGet<TData = Awaited<ReturnType<typeof skillsGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof skillsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSkillsGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Update an existing skill by ID
 * @summary Update a skill
 */
export const skillsUpdate = (
    id: string,
    skillsUpdateBody: BodyType<SkillsUpdateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Skill>(
      {url: `/skills/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: skillsUpdateBody, signal
    },
      options);
    }
  


export const getSkillsUpdateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skillsUpdate>>, TError,{id: string;data: BodyType<SkillsUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof skillsUpdate>>, TError,{id: string;data: BodyType<SkillsUpdateBody>}, TContext> => {

const mutationKey = ['skillsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof skillsUpdate>>, {id: string;data: BodyType<SkillsUpdateBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  skillsUpdate(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SkillsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof skillsUpdate>>>
    export type SkillsUpdateMutationBody = BodyType<SkillsUpdateBody>
    export type SkillsUpdateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Update a skill
 */
export const useSkillsUpdate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skillsUpdate>>, TError,{id: string;data: BodyType<SkillsUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof skillsUpdate>>,
        TError,
        {id: string;data: BodyType<SkillsUpdateBody>},
        TContext
      > => {
      return useMutation(getSkillsUpdateMutationOptions(options), queryClient);
    }
    
/**
 * Delete an existing skill by ID
 * @summary Delete a skill
 */
export const skillsDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/skills/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getSkillsDeleteMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skillsDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof skillsDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['skillsDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof skillsDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  skillsDelete(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SkillsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof skillsDelete>>>
    
    export type SkillsDeleteMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Delete a skill
 */
export const useSkillsDelete = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof skillsDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof skillsDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getSkillsDeleteMutationOptions(options), queryClient);
    }
    
/**
 * Retrieve a list of all works
 * @summary List all works
 */
export const worksList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Work[]>(
      {url: `/works`, method: 'GET', signal
    },
      options);
    }
  



export const getWorksListQueryKey = () => {
    return [
    `/works`
    ] as const;
    }

    
export const getWorksListQueryOptions = <TData = Awaited<ReturnType<typeof worksList>>, TError = ErrorType<void | ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorksListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof worksList>>> = ({ signal }) => worksList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof worksList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorksListQueryResult = NonNullable<Awaited<ReturnType<typeof worksList>>>
export type WorksListQueryError = ErrorType<void | ErrorResponse>


export function useWorksList<TData = Awaited<ReturnType<typeof worksList>>, TError = ErrorType<void | ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof worksList>>,
          TError,
          Awaited<ReturnType<typeof worksList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorksList<TData = Awaited<ReturnType<typeof worksList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof worksList>>,
          TError,
          Awaited<ReturnType<typeof worksList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorksList<TData = Awaited<ReturnType<typeof worksList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all works
 */

export function useWorksList<TData = Awaited<ReturnType<typeof worksList>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorksListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Create a new work with the provided details
 * @summary Create a new work
 */
export const worksCreate = (
    worksCreateBody: BodyType<WorksCreateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Work>(
      {url: `/works`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: worksCreateBody, signal
    },
      options);
    }
  


export const getWorksCreateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof worksCreate>>, TError,{data: BodyType<WorksCreateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof worksCreate>>, TError,{data: BodyType<WorksCreateBody>}, TContext> => {

const mutationKey = ['worksCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof worksCreate>>, {data: BodyType<WorksCreateBody>}> = (props) => {
          const {data} = props ?? {};

          return  worksCreate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WorksCreateMutationResult = NonNullable<Awaited<ReturnType<typeof worksCreate>>>
    export type WorksCreateMutationBody = BodyType<WorksCreateBody>
    export type WorksCreateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Create a new work
 */
export const useWorksCreate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof worksCreate>>, TError,{data: BodyType<WorksCreateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof worksCreate>>,
        TError,
        {data: BodyType<WorksCreateBody>},
        TContext
      > => {
      return useMutation(getWorksCreateMutationOptions(options), queryClient);
    }
    
/**
 * Retrieve a single work by ID
 * @summary Get a work
 */
export const worksGet = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Work>(
      {url: `/works/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getWorksGetQueryKey = (id: string,) => {
    return [
    `/works/${id}`
    ] as const;
    }

    
export const getWorksGetQueryOptions = <TData = Awaited<ReturnType<typeof worksGet>>, TError = ErrorType<ErrorResponse | void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorksGetQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof worksGet>>> = ({ signal }) => worksGet(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof worksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorksGetQueryResult = NonNullable<Awaited<ReturnType<typeof worksGet>>>
export type WorksGetQueryError = ErrorType<ErrorResponse | void>


export function useWorksGet<TData = Awaited<ReturnType<typeof worksGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof worksGet>>,
          TError,
          Awaited<ReturnType<typeof worksGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorksGet<TData = Awaited<ReturnType<typeof worksGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof worksGet>>,
          TError,
          Awaited<ReturnType<typeof worksGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorksGet<TData = Awaited<ReturnType<typeof worksGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a work
 */

export function useWorksGet<TData = Awaited<ReturnType<typeof worksGet>>, TError = ErrorType<ErrorResponse | void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof worksGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorksGetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Update an existing work by ID
 * @summary Update a work
 */
export const worksUpdate = (
    id: string,
    worksUpdateBody: BodyType<WorksUpdateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Work>(
      {url: `/works/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: worksUpdateBody, signal
    },
      options);
    }
  


export const getWorksUpdateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof worksUpdate>>, TError,{id: string;data: BodyType<WorksUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof worksUpdate>>, TError,{id: string;data: BodyType<WorksUpdateBody>}, TContext> => {

const mutationKey = ['worksUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof worksUpdate>>, {id: string;data: BodyType<WorksUpdateBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  worksUpdate(id,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WorksUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof worksUpdate>>>
    export type WorksUpdateMutationBody = BodyType<WorksUpdateBody>
    export type WorksUpdateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Update a work
 */
export const useWorksUpdate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof worksUpdate>>, TError,{id: string;data: BodyType<WorksUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof worksUpdate>>,
        TError,
        {id: string;data: BodyType<WorksUpdateBody>},
        TContext
      > => {
      return useMutation(getWorksUpdateMutationOptions(options), queryClient);
    }
    
/**
 * Delete an existing work by ID
 * @summary Delete a work
 */
export const worksDelete = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/works/${id}`, method: 'DELETE', signal
    },
      options);
    }
  


export const getWorksDeleteMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof worksDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof worksDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['worksDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof worksDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  worksDelete(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WorksDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof worksDelete>>>
    
    export type WorksDeleteMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Delete a work
 */
export const useWorksDelete = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof worksDelete>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof worksDelete>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getWorksDeleteMutationOptions(options), queryClient);
    }
    
/**
 * Retrieve the profile
 * @summary Get profile
 */
export const profileGet = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Profile>(
      {url: `/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getProfileGetQueryKey = () => {
    return [
    `/profile`
    ] as const;
    }

    
export const getProfileGetQueryOptions = <TData = Awaited<ReturnType<typeof profileGet>>, TError = ErrorType<void | ErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProfileGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof profileGet>>> = ({ signal }) => profileGet(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof profileGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProfileGetQueryResult = NonNullable<Awaited<ReturnType<typeof profileGet>>>
export type ProfileGetQueryError = ErrorType<void | ErrorResponse>


export function useProfileGet<TData = Awaited<ReturnType<typeof profileGet>>, TError = ErrorType<void | ErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileGet>>,
          TError,
          Awaited<ReturnType<typeof profileGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileGet<TData = Awaited<ReturnType<typeof profileGet>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileGet>>,
          TError,
          Awaited<ReturnType<typeof profileGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProfileGet<TData = Awaited<ReturnType<typeof profileGet>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get profile
 */

export function useProfileGet<TData = Awaited<ReturnType<typeof profileGet>>, TError = ErrorType<void | ErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof profileGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProfileGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Create or update the profile (upsert)
 * @summary Update profile
 */
export const profileUpdate = (
    profileUpdateBody: BodyType<ProfileUpdateBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Profile>(
      {url: `/profile`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: profileUpdateBody, signal
    },
      options);
    }
  


export const getProfileUpdateMutationOptions = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileUpdate>>, TError,{data: BodyType<ProfileUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof profileUpdate>>, TError,{data: BodyType<ProfileUpdateBody>}, TContext> => {

const mutationKey = ['profileUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileUpdate>>, {data: BodyType<ProfileUpdateBody>}> = (props) => {
          const {data} = props ?? {};

          return  profileUpdate(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProfileUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof profileUpdate>>>
    export type ProfileUpdateMutationBody = BodyType<ProfileUpdateBody>
    export type ProfileUpdateMutationError = ErrorType<ErrorResponse | void>

    /**
 * @summary Update profile
 */
export const useProfileUpdate = <TError = ErrorType<ErrorResponse | void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof profileUpdate>>, TError,{data: BodyType<ProfileUpdateBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof profileUpdate>>,
        TError,
        {data: BodyType<ProfileUpdateBody>},
        TContext
      > => {
      return useMutation(getProfileUpdateMutationOptions(options), queryClient);
    }
