/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Source platform
 * @nullable
 */
export type ArticleSource = typeof ArticleSource[keyof typeof ArticleSource] | null;


export const ArticleSource = {
  zenn: 'zenn',
  qiita: 'qiita',
} as const;
