/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorResponse {
  /** Error message describing what went wrong */
  message: string;
}
