/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export interface Profile {
  /** Name */
  name: string;
  /** Birthday (ISO 8601) */
  birthday: string;
  /** Location */
  location: string;
  /** School */
  school: string;
  /** Image URL */
  image_url: string;
  /** X URL */
  x: string;
  /** GitHub URL */
  github: string;
  /** Zenn URL */
  zenn: string;
  /** Qiita URL */
  qiita: string;
}
