/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export type UploadsPresignBody = {
  /** Name of the file to upload */
  filename: string;
  /** MIME type of the file */
  content_type: string;
};
