/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export type WorksCreateBody = {
  /** Title of the work */
  title: string;
  /** URL-friendly slug for the work */
  slug: string;
  /** Content of the work */
  content: string;
  /** Thumbnail URL for the work */
  thumbnail: string;
};
