// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=works
//

// Package works is a generated GoMock package.
package works

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateWork mocks base method.
func (m *MockServiceInterface) CreateWork(ctx context.Context, title, slug, content, thumbnail string) (*Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWork", ctx, title, slug, content, thumbnail)
	ret0, _ := ret[0].(*Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWork indicates an expected call of CreateWork.
func (mr *MockServiceInterfaceMockRecorder) CreateWork(ctx, title, slug, content, thumbnail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWork", reflect.TypeOf((*MockServiceInterface)(nil).CreateWork), ctx, title, slug, content, thumbnail)
}

// DeleteWork mocks base method.
func (m *MockServiceInterface) DeleteWork(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWork", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWork indicates an expected call of DeleteWork.
func (mr *MockServiceInterfaceMockRecorder) DeleteWork(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWork", reflect.TypeOf((*MockServiceInterface)(nil).DeleteWork), ctx, id)
}

// GetWork mocks base method.
func (m *MockServiceInterface) GetWork(ctx context.Context, id string) (*Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWork", ctx, id)
	ret0, _ := ret[0].(*Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWork indicates an expected call of GetWork.
func (mr *MockServiceInterfaceMockRecorder) GetWork(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWork", reflect.TypeOf((*MockServiceInterface)(nil).GetWork), ctx, id)
}

// ListWorks mocks base method.
func (m *MockServiceInterface) ListWorks(ctx context.Context) ([]Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorks", ctx)
	ret0, _ := ret[0].([]Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorks indicates an expected call of ListWorks.
func (mr *MockServiceInterfaceMockRecorder) ListWorks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorks", reflect.TypeOf((*MockServiceInterface)(nil).ListWorks), ctx)
}

// UpdateWork mocks base method.
func (m *MockServiceInterface) UpdateWork(ctx context.Context, id, title, slug, content, thumbnail string) (*Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWork", ctx, id, title, slug, content, thumbnail)
	ret0, _ := ret[0].(*Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWork indicates an expected call of UpdateWork.
func (mr *MockServiceInterfaceMockRecorder) UpdateWork(ctx, id, title, slug, content, thumbnail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWork", reflect.TypeOf((*MockServiceInterface)(nil).UpdateWork), ctx, id, title, slug, content, thumbnail)
}
