namespace NodeJS {
  interface ProcessEnv {
    // Cognito
    NEXT_PUBLIC_AWS_COGNITO_USER_POOL_ID: string;
    NEXT_PUBLIC_AWS_COGNITO_USER_POOL_CLIENT_ID: string;
    NEXT_PUBLIC_AWS_COGNITO_OAUTH_DOMAIN: string;
    NEXT_PUBLIC_AWS_COGNITO_OAUTH_REDIRECT_SIGNIN: string;
    NEXT_PUBLIC_AWS_COGNITO_OAUTH_REDIRECT_SIGNOUT: string;
    AWS_COGNITO_INTERNAL_USER_POOL_CLIENT_ID: string;
    AWS_COGNITO_INTERNAL_USER_POOL_CLIENT_SECRET: string;
    // API
    NEXT_PUBLIC_API_BASE_URL: string;
  }
}
