/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * keitaito.net Activities API
 * OpenAPI spec version: 1.0.0
 */

export interface Activity {
  /** Unique identifier for the activity */
  id: string;
  /** Title of the activity */
  title: string;
  /** Date of the activity */
  date: string;
  /** Detailed description of the activity */
  description: string;
}
