/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */
import type { ArticleSource } from './article-source';

export interface Article {
  /** Title of the article */
  title: string;
  /** URL of the article */
  url: string;
  /** Number of likes */
  liked_count: number;
  /** Publication date */
  published_at: string;
  /**
   * Source platform
   * @nullable
   */
  source?: ArticleSource;
}
