/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export type ContactUpdateBody = {
  /** Email address */
  email: string;
  /** X (Twitter) username */
  x: string;
};
