/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export interface PresignResponse {
  /** Presigned PUT URL for uploading the file */
  upload_url: string;
  /** S3 object key for the uploaded file */
  key: string;
}
