/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * keitaito.net API
 * OpenAPI spec version: 1.0.0
 */

export type SkillsUpdateBody = {
  /** Name of the skill */
  name: string;
  /** URL to the skill icon */
  icon_url: string;
};
