// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=skills
//

// Package skills is a generated GoMock package.
package skills

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateSkill mocks base method.
func (m *MockServiceInterface) CreateSkill(ctx context.Context, name, iconURL string) (*Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSkill", ctx, name, iconURL)
	ret0, _ := ret[0].(*Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSkill indicates an expected call of CreateSkill.
func (mr *MockServiceInterfaceMockRecorder) CreateSkill(ctx, name, iconURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSkill", reflect.TypeOf((*MockServiceInterface)(nil).CreateSkill), ctx, name, iconURL)
}

// DeleteSkill mocks base method.
func (m *MockServiceInterface) DeleteSkill(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSkill", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSkill indicates an expected call of DeleteSkill.
func (mr *MockServiceInterfaceMockRecorder) DeleteSkill(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSkill", reflect.TypeOf((*MockServiceInterface)(nil).DeleteSkill), ctx, id)
}

// GetSkill mocks base method.
func (m *MockServiceInterface) GetSkill(ctx context.Context, id string) (*Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSkill", ctx, id)
	ret0, _ := ret[0].(*Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSkill indicates an expected call of GetSkill.
func (mr *MockServiceInterfaceMockRecorder) GetSkill(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSkill", reflect.TypeOf((*MockServiceInterface)(nil).GetSkill), ctx, id)
}

// ListSkills mocks base method.
func (m *MockServiceInterface) ListSkills(ctx context.Context) ([]Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSkills", ctx)
	ret0, _ := ret[0].([]Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkills indicates an expected call of ListSkills.
func (mr *MockServiceInterfaceMockRecorder) ListSkills(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkills", reflect.TypeOf((*MockServiceInterface)(nil).ListSkills), ctx)
}

// UpdateSkill mocks base method.
func (m *MockServiceInterface) UpdateSkill(ctx context.Context, id, name, iconURL string) (*Skill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSkill", ctx, id, name, iconURL)
	ret0, _ := ret[0].(*Skill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSkill indicates an expected call of UpdateSkill.
func (mr *MockServiceInterfaceMockRecorder) UpdateSkill(ctx, id, name, iconURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSkill", reflect.TypeOf((*MockServiceInterface)(nil).UpdateSkill), ctx, id, name, iconURL)
}
