// Code generated by MockGen. DO NOT EDIT.
// Source: collector.go
//
// Generated by this command:
//
//	mockgen -source=collector.go -destination=collector_mock.go -package=articles
//

// Package articles is a generated GoMock package.
package articles

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPClient)(nil).Do), req)
}

// MockCollectorServiceInterface is a mock of CollectorServiceInterface interface.
type MockCollectorServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCollectorServiceInterfaceMockRecorder is the mock recorder for MockCollectorServiceInterface.
type MockCollectorServiceInterfaceMockRecorder struct {
	mock *MockCollectorServiceInterface
}

// NewMockCollectorServiceInterface creates a new mock instance.
func NewMockCollectorServiceInterface(ctrl *gomock.Controller) *MockCollectorServiceInterface {
	mock := &MockCollectorServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCollectorServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectorServiceInterface) EXPECT() *MockCollectorServiceInterfaceMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockCollectorServiceInterface) Collect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockCollectorServiceInterfaceMockRecorder) Collect(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockCollectorServiceInterface)(nil).Collect), ctx)
}
