/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all activities
         * @description Retrieve a list of all activities
         */
        get: operations["activities_list"];
        put?: never;
        /**
         * Create a new activity
         * @description Create a new activity with the provided details
         */
        post: operations["activities_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an activity
         * @description Retrieve a single activity by ID
         */
        get: operations["activities_get"];
        /**
         * Update an activity
         * @description Update an existing activity by ID
         */
        put: operations["activities_update"];
        post?: never;
        /**
         * Delete an activity
         * @description Delete an existing activity by ID
         */
        delete: operations["activities_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all skills
         * @description Retrieve a list of all skills
         */
        get: operations["skills_list"];
        put?: never;
        /**
         * Create a new skill
         * @description Create a new skill with the provided details
         */
        post: operations["skills_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a skill
         * @description Retrieve a single skill by ID
         */
        get: operations["skills_get"];
        /**
         * Update a skill
         * @description Update an existing skill by ID
         */
        put: operations["skills_update"];
        post?: never;
        /**
         * Delete a skill
         * @description Delete an existing skill by ID
         */
        delete: operations["skills_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all works
         * @description Retrieve a list of all works
         */
        get: operations["works_list"];
        put?: never;
        /**
         * Create a new work
         * @description Create a new work with the provided details
         */
        post: operations["works_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a work
         * @description Retrieve a single work by ID
         */
        get: operations["works_get"];
        /**
         * Update a work
         * @description Update an existing work by ID
         */
        put: operations["works_update"];
        post?: never;
        /**
         * Delete a work
         * @description Delete an existing work by ID
         */
        delete: operations["works_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get profile
         * @description Retrieve the profile
         */
        get: operations["profile_get"];
        /**
         * Update profile
         * @description Create or update the profile (upsert)
         */
        put: operations["profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get contact
         * @description Retrieve the contact information
         */
        get: operations["contact_get"];
        /**
         * Update contact
         * @description Create or update the contact information (upsert)
         */
        put: operations["contact_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cached articles
         * @description Retrieve a list of cached articles from Zenn and Qiita
         */
        get: operations["articles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually trigger articles collection
         * @description Fetch latest articles from Zenn and Qiita and update the cache
         */
        post: operations["articles_collect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a presigned URL for file upload
         * @description Generate a presigned PUT URL for uploading a file directly to S3
         */
        post: operations["uploads_presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activity: {
            /**
             * Format: uuid
             * @description Unique identifier for the activity
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Title of the activity
             * @example New Project Launch
             */
            title: string;
            /**
             * @description Date of the activity
             * @example 2024-01
             */
            date: string;
            /**
             * @description Detailed description of the activity
             * @example Launched a new portfolio website using Next.js and AWS
             */
            description: string;
        };
        Skill: {
            /**
             * Format: uuid
             * @description Unique identifier for the skill
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Name of the skill
             * @example Go
             */
            name: string;
            /**
             * @description URL to the skill icon
             * @example https://example.com/icons/go.png
             */
            icon_url: string;
        };
        Work: {
            /**
             * Format: uuid
             * @description Unique identifier for the work
             * @example 770e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Title of the work
             * @example Portfolio Website
             */
            title: string;
            /**
             * @description URL-friendly slug for the work
             * @example portfolio-website
             */
            slug: string;
            /**
             * @description Content of the work
             * @example A personal portfolio website built with Next.js and AWS
             */
            content: string;
            /**
             * @description Thumbnail URL for the work
             * @example https://example.com/thumbnails/portfolio.png
             */
            thumbnail: string;
        };
        Profile: {
            /**
             * @description Name
             * @example Keita Ito
             */
            name: string;
            /**
             * Format: date
             * @description Birthday (ISO 8601)
             * @example 2004-07-09
             */
            birthday: string;
            /**
             * @description Location
             * @example Tokyo
             */
            location: string;
            /**
             * @description School
             * @example University of Tokyo
             */
            school: string;
            /**
             * Format: uri
             * @description Image URL
             * @example https://example.com/image.png
             */
            image_url: string;
            /**
             * Format: uri
             * @description X URL
             * @example https://x.com/keitaito
             */
            x: string;
            /**
             * Format: uri
             * @description GitHub URL
             * @example https://github.com/keitaito
             */
            github: string;
            /**
             * Format: uri
             * @description Zenn URL
             * @example https://zenn.dev/keitaito
             */
            zenn: string;
            /**
             * Format: uri
             * @description Qiita URL
             * @example https://qiita.com/keitaito
             */
            qiita: string;
        };
        Contact: {
            /**
             * Format: email
             * @description Email address
             * @example johndoe@example.com
             */
            email: string;
            /**
             * @description X (Twitter) username
             * @example johndoe
             */
            x: string;
        };
        Article: {
            /**
             * @description Title of the article
             * @example Building a portfolio with Next.js
             */
            title: string;
            /**
             * Format: uri
             * @description URL of the article
             * @example https://zenn.dev/kk79it/articles/example
             */
            url: string;
            /**
             * @description Number of likes
             * @example 10
             */
            liked_count: number;
            /**
             * Format: date-time
             * @description Publication date
             * @example 2025-01-01T00:00:00+09:00
             */
            published_at: string;
            /**
             * @description Source platform
             * @example zenn
             * @enum {string|null}
             */
            source?: "zenn" | "qiita" | null;
        };
        PresignResponse: {
            /**
             * @description Presigned PUT URL for uploading the file
             * @example https://s3.amazonaws.com/bucket/uuid/photo.png?...
             */
            upload_url: string;
            /**
             * @description S3 object key for the uploaded file
             * @example 550e8400-e29b-41d4-a716-446655440000/photo.png
             */
            key: string;
        };
        ErrorResponse: {
            /**
             * @description Error message describing what went wrong
             * @example Activity not found (id: 550e8400-e29b-41d4-a716-446655440000)
             */
            message: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Activity UUID */
        ActivityId: string;
        /** @description Skill UUID */
        SkillId: string;
        /** @description Work UUID */
        WorkId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    activities_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activities_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Title of the activity
                     * @example New Project Launch
                     */
                    title: string;
                    /**
                     * @description Date of the activity
                     * @example 2024-01
                     */
                    date: string;
                    /**
                     * @description Detailed description of the activity
                     * @example Launched a new portfolio website using Next.js and AWS
                     */
                    description: string;
                };
            };
        };
        responses: {
            /** @description Activity created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity UUID */
                id: components["parameters"]["ActivityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activities_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity UUID */
                id: components["parameters"]["ActivityId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Title of the activity
                     * @example Updated Project Launch
                     */
                    title: string;
                    /**
                     * @description Date of the activity
                     * @example 2024-01
                     */
                    date: string;
                    /**
                     * @description Detailed description of the activity
                     * @example Updated the portfolio website with new features
                     */
                    description: string;
                };
            };
        };
        responses: {
            /** @description Activity updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activities_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Activity UUID */
                id: components["parameters"]["ActivityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    skills_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    skills_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Name of the skill
                     * @example Go
                     */
                    name: string;
                    /**
                     * @description URL to the skill icon
                     * @example https://example.com/icons/go.png
                     */
                    icon_url: string;
                };
            };
        };
        responses: {
            /** @description Skill created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill UUID */
                id: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Skill not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    skills_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill UUID */
                id: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Name of the skill
                     * @example Go
                     */
                    name: string;
                    /**
                     * @description URL to the skill icon
                     * @example https://example.com/icons/go-updated.png
                     */
                    icon_url: string;
                };
            };
        };
        responses: {
            /** @description Skill updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Skill not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    skills_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill UUID */
                id: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Skill not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    works_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    works_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Title of the work
                     * @example Portfolio Website
                     */
                    title: string;
                    /**
                     * @description URL-friendly slug for the work
                     * @example portfolio-website
                     */
                    slug: string;
                    /**
                     * @description Content of the work
                     * @example A personal portfolio website built with Next.js and AWS
                     */
                    content: string;
                    /**
                     * @description Thumbnail URL for the work
                     * @example https://example.com/thumbnails/portfolio.png
                     */
                    thumbnail: string;
                };
            };
        };
        responses: {
            /** @description Work created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    works_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work UUID */
                id: components["parameters"]["WorkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Work not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    works_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work UUID */
                id: components["parameters"]["WorkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Title of the work
                     * @example Updated Portfolio Website
                     */
                    title: string;
                    /**
                     * @description URL-friendly slug for the work
                     * @example portfolio-website
                     */
                    slug: string;
                    /**
                     * @description Content of the work
                     * @example Updated portfolio website with new features
                     */
                    content: string;
                    /**
                     * @description Thumbnail URL for the work
                     * @example https://example.com/thumbnails/portfolio-updated.png
                     */
                    thumbnail: string;
                };
            };
        };
        responses: {
            /** @description Work updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Work"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Work not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    works_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Work UUID */
                id: components["parameters"]["WorkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Work deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Work not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Name
                     * @example Keita Ito
                     */
                    name: string;
                    /**
                     * Format: date
                     * @description Birthday (ISO 8601)
                     * @example 2004-07-09
                     */
                    birthday: string;
                    /**
                     * @description Location
                     * @example Tokyo
                     */
                    location: string;
                    /**
                     * @description School
                     * @example University of Tokyo
                     */
                    school: string;
                    /**
                     * Format: uri
                     * @description Image URL
                     * @example https://example.com/image.png
                     */
                    image_url: string;
                    /**
                     * Format: uri
                     * @description X URL
                     * @example https://x.com/keitaito
                     */
                    x: string;
                    /**
                     * Format: uri
                     * @description GitHub URL
                     * @example https://github.com/keitaito
                     */
                    github: string;
                    /**
                     * Format: uri
                     * @description Zenn URL
                     * @example https://zenn.dev/keitaito
                     */
                    zenn: string;
                    /**
                     * Format: uri
                     * @description Qiita URL
                     * @example https://qiita.com/keitaito
                     */
                    qiita: string;
                };
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    contact_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    contact_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description Email address
                     * @example johndoe@example.com
                     */
                    email: string;
                    /**
                     * @description X (Twitter) username
                     * @example johndoe
                     */
                    x: string;
                };
            };
        };
        responses: {
            /** @description Contact updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    articles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    articles_collect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Articles collected successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploads_presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Name of the file to upload
                     * @example photo.png
                     */
                    filename: string;
                    /**
                     * @description MIME type of the file
                     * @example image/png
                     */
                    content_type: string;
                };
            };
        };
        responses: {
            /** @description Presigned URL generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
export enum ApiPaths {
    activities_list = "/activities",
    activities_create = "/activities",
    activities_get = "/activities/{id}",
    activities_update = "/activities/{id}",
    activities_delete = "/activities/{id}",
    skills_list = "/skills",
    skills_create = "/skills",
    skills_get = "/skills/{id}",
    skills_update = "/skills/{id}",
    skills_delete = "/skills/{id}",
    works_list = "/works",
    works_create = "/works",
    works_get = "/works/{id}",
    works_update = "/works/{id}",
    works_delete = "/works/{id}",
    profile_get = "/profile",
    profile_update = "/profile",
    contact_get = "/contact",
    contact_update = "/contact",
    articles_list = "/articles",
    articles_collect = "/articles/collect",
    uploads_presign = "/uploads/presign"
}
