// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ke1ta1to/keitaito.net/apps/functions/internal/uploads (interfaces: Presigner)
//
// Generated by this command:
//
//	mockgen -typed -destination=presigner_mock_test.go -package=uploads . Presigner
//

// Package uploads is a generated GoMock package.
package uploads

import (
	context "context"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockPresigner is a mock of Presigner interface.
type MockPresigner struct {
	ctrl     *gomock.Controller
	recorder *MockPresignerMockRecorder
	isgomock struct{}
}

// MockPresignerMockRecorder is the mock recorder for MockPresigner.
type MockPresignerMockRecorder struct {
	mock *MockPresigner
}

// NewMockPresigner creates a new mock instance.
func NewMockPresigner(ctrl *gomock.Controller) *MockPresigner {
	mock := &MockPresigner{ctrl: ctrl}
	mock.recorder = &MockPresignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresigner) EXPECT() *MockPresignerMockRecorder {
	return m.recorder
}

// PresignPutObject mocks base method.
func (m *MockPresigner) PresignPutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignPutObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockPresignerMockRecorder) PresignPutObject(ctx, params any, optFns ...any) *MockPresignerPresignPutObjectCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject", reflect.TypeOf((*MockPresigner)(nil).PresignPutObject), varargs...)
	return &MockPresignerPresignPutObjectCall{Call: call}
}

// MockPresignerPresignPutObjectCall wrap *gomock.Call
type MockPresignerPresignPutObjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPresignerPresignPutObjectCall) Return(arg0 *v4.PresignedHTTPRequest, arg1 error) *MockPresignerPresignPutObjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPresignerPresignPutObjectCall) Do(f func(context.Context, *s3.PutObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockPresignerPresignPutObjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPresignerPresignPutObjectCall) DoAndReturn(f func(context.Context, *s3.PutObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *MockPresignerPresignPutObjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
