// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=activities
//

// Package activities is a generated GoMock package.
package activities

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateActivity mocks base method.
func (m *MockServiceInterface) CreateActivity(ctx context.Context, title, date, description string) (*Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, title, date, description)
	ret0, _ := ret[0].(*Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockServiceInterfaceMockRecorder) CreateActivity(ctx, title, date, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockServiceInterface)(nil).CreateActivity), ctx, title, date, description)
}

// DeleteActivity mocks base method.
func (m *MockServiceInterface) DeleteActivity(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockServiceInterfaceMockRecorder) DeleteActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockServiceInterface)(nil).DeleteActivity), ctx, id)
}

// GetActivity mocks base method.
func (m *MockServiceInterface) GetActivity(ctx context.Context, id string) (*Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivity", ctx, id)
	ret0, _ := ret[0].(*Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivity indicates an expected call of GetActivity.
func (mr *MockServiceInterfaceMockRecorder) GetActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivity", reflect.TypeOf((*MockServiceInterface)(nil).GetActivity), ctx, id)
}

// ListActivities mocks base method.
func (m *MockServiceInterface) ListActivities(ctx context.Context) ([]Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivities", ctx)
	ret0, _ := ret[0].([]Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivities indicates an expected call of ListActivities.
func (mr *MockServiceInterfaceMockRecorder) ListActivities(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivities", reflect.TypeOf((*MockServiceInterface)(nil).ListActivities), ctx)
}

// UpdateActivity mocks base method.
func (m *MockServiceInterface) UpdateActivity(ctx context.Context, id, title, date, description string) (*Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, id, title, date, description)
	ret0, _ := ret[0].(*Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockServiceInterfaceMockRecorder) UpdateActivity(ctx, id, title, date, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockServiceInterface)(nil).UpdateActivity), ctx, id, title, date, description)
}
